name: Continuous Integration 
on: 
  pull_request:
    brances:
      - main

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        users: action/checkout@v4
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
      with:
        linter: pylint